version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/dangder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev

  my-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'dangder'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  # Redis
  my-redis:
    image: redis:latest
    ports:
      - 6379:6379
